// src/api/nfs-server.js
const path = require('path');
const fs = require('fs');
const { exec } = require('child_process');
const { promisify } = require('util');
const os = require('os');
const execAsync = promisify(exec);

const NFS_EXPORTS_PATH = '/etc/exports';
const NFS_SERVICE_NAME = 'nfs-server';

module.exports = function(app, requireAuth) {

  // Sprawdź status serwera NFS
  app.get('/api/nfs-server/status', requireAuth, async (req, res) => {
    try {
      // Sprawdź czy serwer NFS jest zainstalowany
      let installed = false;
      let active = false;
      let version = '';
      
      try {
        const { stdout: pkgCheck } = await execAsync('dpkg -l | grep nfs-kernel-server || rpm -qa | grep nfs-utils || true');
        installed = pkgCheck.length > 0;
      } catch (e) {}
      
      try {
        const { stdout: serviceCheck } = await execAsync('systemctl is-active nfs-server || systemctl is-active nfs-kernel-server || true');
        active = serviceCheck.trim() === 'active';
      } catch (e) {}
      
      try {
        const { stdout: versionCheck } = await execAsync('nfsstat -m | head -1 || true');
        const match = versionCheck.match(/nfsv?(\d+(\.\d+)?)/i);
        version = match ? match[1] : 'unknown';
      } catch (e) {}
      
      res.json({
        success: true,
        installed,
        active,
        version,
        hostname: os.hostname(),
        ipAddresses: getLocalIPs()
      });
    } catch (error) {
      res.status(500).json({
        success: false,
        error: 'Failed to check NFS server status',
        details: error.message
      });
    }
  });

  // Zarządzanie usługą NFS
  app.post('/api/nfs-server/toggle', requireAuth, async (req, res) => {
    const { action } = req.body;
    
    if (!['start', 'stop', 'restart', 'reload'].includes(action)) {
      return res.status(400).json({ success: false, error: 'Invalid action' });
    }
    
    try {
      await execAsync(`systemctl ${action} ${NFS_SERVICE_NAME} || systemctl ${action} nfs-kernel-server || true`);
      res.json({ success: true, message: `NFS server ${action}ed` });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Pobierz listę eksportów
  app.get('/api/nfs-server/exports', requireAuth, async (req, res) => {
    try {
      const exports = [];
      
      if (fs.existsSync(NFS_EXPORTS_PATH)) {
        const content = fs.readFileSync(NFS_EXPORTS_PATH, 'utf8');
        const lines = content.split('\n');
        
        lines.forEach((line, index) => {
          line = line.trim();
          if (line && !line.startsWith('#')) {
            // Format: /path/to/export client1(options) client2(options)
            const parts = line.split(/\s+/);
            if (parts.length >= 2) {
              const exportPath = parts[0];
              const clients = [];
              
              for (let i = 1; i < parts.length; i++) {
                const clientPart = parts[i];
                const clientMatch = clientPart.match(/([^(]+)\(([^)]+)\)/);
                if (clientMatch) {
                  clients.push({
                    client: clientMatch[1],
                    options: clientMatch[2].split(',')
                  });
                } else {
                  clients.push({
                    client: clientPart,
                    options: ['ro']
                  });
                }
              }
              
              exports.push({
                id: index,
                path: exportPath,
                clients,
                enabled: true,
                comment: ''
              });
            }
          } else if (line.startsWith('#')) {
            // Komentarz
          }
        });
      }
      
      // Dodaj przykładowy export jeśli brak
      if (exports.length === 0) {
        exports.push({
          id: 'example',
          path: '/srv/nfs/share',
          clients: [
            { client: '192.168.1.0/24', options: ['rw', 'sync', 'no_subtree_check'] }
          ],
          enabled: false,
          comment: '# Example export'
        });
      }
      
      res.json({ success: true, exports });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Zapisz eksporty
  app.post('/api/nfs-server/exports', requireAuth, async (req, res) => {
    const { exports } = req.body;
    
    try {
      // Utwórz kopię zapasową
      if (fs.existsSync(NFS_EXPORTS_PATH)) {
        const backupPath = `${NFS_EXPORTS_PATH}.backup.${Date.now()}`;
        fs.copyFileSync(NFS_EXPORTS_PATH, backupPath);
      }
      
      // Generuj zawartość
      let content = '# NFS Exports - Generated by NAS Panel\n';
      content += '# Format: directory client1(options) client2(options)\n\n';
      
      exports.forEach(exp => {
        if (exp.enabled && exp.path) {
          const clientsStr = exp.clients.map(c => 
            `${c.client}(${c.options.join(',')})`
          ).join(' ');
          content += `${exp.path} ${clientsStr}\n`;
        } else if (exp.comment) {
          content += `# ${exp.comment}\n`;
        }
      });
      
      fs.writeFileSync(NFS_EXPORTS_PATH, content);
      
      // Przeładuj eksporty
      try {
        await execAsync('exportfs -ra');
      } catch (e) {
        console.log('Exportfs reload error:', e.message);
      }
      
      res.json({ success: true, message: 'Exports saved successfully' });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Dodaj nowy eksport
  app.post('/api/nfs-server/exports/add', requireAuth, async (req, res) => {
    const { path: exportPath, clients } = req.body;
    
    if (!exportPath) {
      return res.status(400).json({ success: false, error: 'Export path is required' });
    }
    
    try {
      // Sprawdź czy ścieżka istnieje
      if (!fs.existsSync(exportPath)) {
        fs.mkdirSync(exportPath, { recursive: true, mode: 0o755 });
      }
      
      // Dodaj do pliku eksportów
      let content = '';
      if (fs.existsSync(NFS_EXPORTS_PATH)) {
        content = fs.readFileSync(NFS_EXPORTS_PATH, 'utf8');
      }
      
      const clientsStr = clients.map(c => 
        `${c.client}(${c.options.join(',')})`
      ).join(' ');
      
      content += `\n${exportPath} ${clientsStr}`;
      fs.writeFileSync(NFS_EXPORTS_PATH, content);
      
      // Przeładuj eksporty
      await execAsync('exportfs -ra');
      
      res.json({ success: true, message: 'Export added successfully' });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Usuń eksport
  app.delete('/api/nfs-server/exports/:id', requireAuth, async (req, res) => {
    const { id } = req.params;
    
    try {
      const content = fs.readFileSync(NFS_EXPORTS_PATH, 'utf8');
      const lines = content.split('\n');
      const newLines = lines.filter((line, index) => index.toString() !== id);
      
      fs.writeFileSync(NFS_EXPORTS_PATH, newLines.join('\n'));
      
      // Przeładuj eksporty
      await execAsync('exportfs -ra');
      
      res.json({ success: true, message: 'Export removed successfully' });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Pobierz statystyki NFS
  app.get('/api/nfs-server/stats', requireAuth, async (req, res) => {
    try {
      const stats = {
        activeExports: 0,
        totalClients: 0,
        mountStats: [],
        ioStats: { read: 0, write: 0 }
      };
      
      // Liczba aktywnych eksportów
      try {
        const { stdout } = await execAsync('exportfs -v | grep -c "^/" || true');
        stats.activeExports = parseInt(stdout) || 0;
      } catch (e) {}
      
      // Statystyki montowań
      try {
        const { stdout } = await execAsync('showmount -a || true');
        const lines = stdout.split('\n').slice(1);
        stats.totalClients = lines.filter(l => l.trim()).length;
        stats.mountStats = lines.filter(l => l.trim()).map(l => {
          const parts = l.split(':');
          return { client: parts[0], mount: parts[1] };
        });
      } catch (e) {}
      
      // Statystyki I/O
      try {
        const { stdout } = await execAsync('nfsstat -s | grep -E "read|write" || true');
        const lines = stdout.split('\n');
        lines.forEach(line => {
          if (line.includes('read')) {
            const match = line.match(/(\d+)/);
            stats.ioStats.read = match ? parseInt(match[1]) : 0;
          }
          if (line.includes('write')) {
            const match = line.match(/(\d+)/);
            stats.ioStats.write = match ? parseInt(match[1]) : 0;
          }
        });
      } catch (e) {}
      
      res.json({ success: true, stats });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Pobierz logi NFS
  app.get('/api/nfs-server/logs', requireAuth, async (req, res) => {
    const { lines = 100 } = req.query;
    
    try {
      const { stdout } = await execAsync(`journalctl -u nfs-server -n ${lines} --no-pager 2>/dev/null || tail -n ${lines} /var/log/syslog | grep nfs || true`);
      
      const logs = stdout.split('\n')
        .filter(l => l.trim())
        .map(l => {
          const match = l.match(/^(\w+\s+\d+\s+\d+:\d+:\d+).*nfs.*?:\s*(.*)$/i);
          return {
            timestamp: match ? match[1] : new Date().toLocaleString(),
            message: match ? match[2] : l,
            level: l.includes('error') ? 'error' : (l.includes('warn') ? 'warning' : 'info')
          };
        });
      
      res.json({ success: true, logs });
    } catch (error) {
      res.status(500).json({ success: false, error: error.message });
    }
  });

  // Test konfiguracji
  app.post('/api/nfs-server/test', requireAuth, async (req, res) => {
    try {
      const { stdout, stderr } = await execAsync('exportfs -v');
      res.json({ 
        success: true, 
        message: 'Configuration test passed',
        details: stdout
      });
    } catch (error) {
      res.status(500).json({ 
        success: false, 
        error: 'Configuration test failed',
        details: error.message
      });
    }
  });

  // Funkcja pomocnicza do pobierania lokalnych IP
  function getLocalIPs() {
    const interfaces = os.networkInterfaces();
    const ips = [];
    
    Object.keys(interfaces).forEach(iface => {
      interfaces[iface].forEach(addr => {
        if (addr.family === 'IPv4' && !addr.internal) {
          ips.push({
            interface: iface,
            ip: addr.address,
            network: `${addr.address.split('.').slice(0, 3).join('.')}.0/24`
          });
        }
      });
    });
    
    return ips;
  }
};