#!/bin/bash

rm -fr /etc/nas-panel

# Stop service before removal
systemctl stop nas-api.service
systemctl disable nas-api.service

systemctl stop nas-webdav.service
systemctl disable nas-webdav.service

exit 0
