version: '3'
services:
  heimdall:
    image: linuxserver/heimdall:latest
    container_name: heimdall
    ports:
      - "8083:80"
      - "8443:443"
    volumes:
      - heimdall_config:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    restart: unless-stopped

volumes:
  heimdall_config: