version: '3'
services:
  librespeed:
    image: linuxserver/librespeed:latest
    container_name: librespeed
    ports:
      - "8081:80"
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped