name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4
    
    - name: Install required system packages
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          debconf \
          nodejs \
          npm \
          sqlite3 \
          ethtool \
          ufw \
          network-manager \
          smartmontools \
          net-tools \
          libc6 \
          iperf3 \
          iproute2 \
          jq \
          python3 \
          make \
          g++ \
          musl-dev \
          samba \
          mdadm \
          lsof \
          rsync \
          curl \
          wget \
          cron \
          libpam0g-dev

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: backend/package-lock.json

    - name: Install dependencies
      working-directory: ./backend
      run: npm ci

    - name: Run build
      working-directory: ./backend
      run: npm run build --if-present

    - name: Run tests
      working-directory: ./backend
      run: npm test
